# Generated by Django 5.0 on 2023-12-30 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre réunion')),
                ('date', models.DateField(verbose_name='Date réunion')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('description', models.TextField(verbose_name='Description de la réunion')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Inviter employés')),
            ],
        ),
    ]
